import express from "express";
import {login,register,logout,sendVerifyOTP,verifyEmail,isAuthenticated,sendResetOtp,resetPassword} from '../controllers/authcontroller.js';
import userAuth from "../middlewears/userAuth.js";
const authRouter=express.Router();
authRouter.post('/register',register);
authRouter.post('/login',login);
authRouter.post('/logout',logout);
authRouter.post('/send-verify-otp',userAuth,sendVerifyOTP);
authRouter.post('/verify-account',userAuth,verifyEmail);
authRouter.get('/is-auth',userAuth,isAuthenticated);
authRouter.post('/sent-reset-otp',sendResetOtp);
authRouter.post('/reset-password',resetPassword);
export default authRouter;