// src/data.js
export const questions = [
  {
    id: 1,
    text: "Inspect a roof for leaks",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 2,
    text: "Use precision machines to build custom metal parts",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 3,
    text: "Analyze the structure of molecules",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 4,
    text: "Do scientific experiments",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 5,
    text: "Design a magazine cover",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 6,
    text: "Paint a portrait",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 7,
    text: "Teach social skills to disabled children",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 8,
    text: "Teach adults to read",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 9,
    text: "Coordinate a business conference",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 10,
    text: "Plan a marketing strategy for a new company",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 11,
    text: "Track monthly expenses for a company",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 12,
    text: "Review financial records for accuracy",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 13,
    text: "Install a hardwood floor",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 14,
    text: "Repair an air conditioning system",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 15,
    text: "Research the properties of nuclear energy",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 16,
    text: "Research a new medicine",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 17,
    text: "Design a greeting card",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 18,
    text: "Illustrate a children’s book",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 19,
    text: "Help a disabled person with their daily routine",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 20,
    text: "Tutor a child with a learning disability",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 21,
    text: "Negotiate business partnerships",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 22,
    text: "Persuade others to my point of view",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 23,
    text: "Keep payroll records",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 24,
    text: "Use spreadsheets to organize financial data",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 25,
    text: "Install an alarm system in a building",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 26,
    text: "Install kitchen cabinets",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 27,
    text: "Look at cells through a microscope",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 28,
    text: "Work in a chemistry lab",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 29,
    text: "Write a poem",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 30,
    text: "Write a script for a television show",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 31,
    text: "Counsel a person recovering from drug addiction",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 32,
    text: "Counsel a person with depression",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 33,
    text: "Hire and fire employees",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 34,
    text: "Close an important business deal",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 35,
    text: "Check tax returns for errors",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 36,
    text: "Calculate the cost of an insurance claim",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 37,
    text: "Build a stone wall",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 38,
    text: "Operate a bulldozer",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 39,
    text: "Analyze soil samples for pollution",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 40,
    text: "Study a fault line to predict earthquakes",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 41,
    text: "Design a billboard advertisement",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 42,
    text: "Edit a movie",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 43,
    text: "Plan educational games for preschool children",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 44,
    text: "Plan activities for elderly people",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 45,
    text: "Lead a team",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 46,
    text: "Start a new business",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 47,
    text: "Calculate the cost of a construction project",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 48,
    text: "Help customers fill out loan applications",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 49,
    text: "Take apart a car engine",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 50,
    text: "Do laboratory tests to diagnose diseases",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 51,
    text: "Compose a song",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 52,
    text: "Help a needy family find appropriate housing",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 53,
    text: "Give a speech in front of many people",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 54,
    text: "Develop a budget for a city government",
    options: ["Strongly Dislike", "Dislike", "Neutral", "Like", "Strongly Like"],
  },
  {
    id: 55,
    text: "I treat everyone with kindness and sympathy.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 56,
    text: "I am always prepared.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 57,
    text: "I don't talk a lot.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 58,
    text: "I am often troubled by negative thoughts.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 59,
    text: "I believe in the importance of art.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 60,
    text: "I have a kind word for everyone.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 61,
    text: "I make plans and stick to them.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 62,
    text: "I stay in the background.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 63,
    text: "I often feel blue.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 64,
    text: "I have a vivid imagination.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 65,
    text: "I criticize other people.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 66,
    text: "I get chores done right away.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 67,
    text: "I am the life of the party.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 68,
    text: "I often worry that I am not good enough.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 69,
    text: "I am not interested in abstract ideas.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 70,
    text: "I stop what I am doing to help other people.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 71,
    text: "I always make good use of my time.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 72,
    text: "I am skilled in handling social situations.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 73,
    text: "I often feel anxious about what could go wrong.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  {
    id: 74,
    text: "I am interested in the meaning of things.",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"],
  },
  { id: 75,
    text: "Original", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] 
  },
  { id: 76, 
    text: "Systematic", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] 
  },
  { id: 77, 
    text: "Shy", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] 
},
  { id: 78,
    text: "Soft-Hearted",
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 79, 
    text: "Tense", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 80, 
    text: "Inquisitive", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 81, 
    text: "Forgetful", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 82, 
    text: "Reserved", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 83, 
    text: "Agreeable", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 84, 
    text: "Nervous", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 85, 
    text: "Creative", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 86, 
    text: "Self-Disciplined", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 87, 
    text: "Outgoing", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 88, 
    text: "Charitable", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 89, 
    text: "Moody", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 90, 
    text: "Imaginative", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 91, 
    text: "Organized", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 92, 
    text: "Talkative", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 93, 
    text: "Humble", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
  { id: 94, 
    text: "Pessimistic", 
    options: ["Strongly Inaccurate", "Inaccurate", "Neutral", "Accurate", "Strongly Accurate"] },
];
