import React from "react";

export default function CareerRoadmap() {
  return (
    <div style={{ padding: "40px", textAlign: "center" }}>
      <h1>Career Roadmap Generator</h1>
      <p>This is a placeholder page. Here you'll get a personalized roadmap generated by AI.</p>
    </div>
  );
}
